# MTG Set Generator Pipeline
# Generates Magic: The Gathering cards with full mechanics, art, and flavor text
#
# Based on the mtgrandom project (~/Dev/mtgrandom/)
# Usage: artgen run pipeline.yaml

name: mtg-set-generator
description: "Generate a complete Magic: The Gathering card set"

# AI Provider Configuration
# Set defaults here, override per-step if needed
providers:
  text: litellm        # Text generation: litellm, gemini
  image: gemini        # Image generation: gemini, dalle, pixellab
  # text_model: gpt-4  # Optional: specify model
  # image_model: imagen-3

# Card data structure
types:
  MagicCard:
    name: text
    concept: text
    color: text
    rarity: text
    card_type: text
    supertype: text
    subtype: text
    power: text
    toughness: text
    mana_cost: text
    rule_text: text
    flavor_text: text
    art_prompt: text
    artist_credit: text

# Set configuration
context:
  set_theme: "A dark gothic horror set inspired by Eastern European folklore, featuring vampires, werewolves, and ancient curses"
  set_size: 6

# Named asset collections
# Cards will be dynamically generated by the generate_card_names step
assets:
  cards:
    type: MagicCard
    generated_by: generate_card_names  # Will be created by this step
    count: "{context.set_size}"  # Expected size

# Output settings
output:
  directory: output/
  naming: "{asset.name}"

state:
  directory: .artgen/

steps:
  # ═══════════════════════════════════════════════════════════════════════════
  # PHASE 1: SET DESIGN (Global/Gather Steps - runs once)
  # ═══════════════════════════════════════════════════════════════════════════

  - id: design_set_mechanics
    type: generate_text
    description: "Design set mechanics and thematic framework"
    prompt: |
      I'm a game designer at Wizards of the Coast designing a new Magic: The Gathering set.
      
      THEME: {context.set_theme}
      TARGET SIZE: {context.set_size} cards
      
      Please design the mechanical framework for this set:
      
      ## 1. Existing Mechanics (choose 6)
      Select 6 existing MTG mechanics that fit this theme. For each:
      - Name and brief rules reminder
      - Why it fits the theme
      - Which colors will use it
      
      ## 2. Signature Mechanic (design 1 new)
      Create one NEW mechanic unique to this set:
      - Name and rules text
      - Flavor justification
      - Complexity level (1-3)
      
      ## 3. Color Themes
      For each of the five colors, describe:
      - Thematic role in this set
      - Primary mechanics
      - Creature types
      
      ## 4. Draft Archetypes
      For each two-color pair (10 total), describe the draft archetype:
      - WU, WB, WR, WG
      - UB, UR, UG
      - BR, BG
      - RG
      
      ## 5. Art Direction
      Describe the visual style:
      - Color palette
      - Artistic influences
      - Key visual motifs
    writes_to: set_mechanics
    cache: true

  - id: write_set_story  
    type: generate_text
    requires: [design_set_mechanics]
    description: "Write narrative story for the set"
    prompt: |
      Based on this Magic set design:
      
      THEME: {context.set_theme}
      
      MECHANICS:
      {step_outputs.design_set_mechanics}
      
      Write a rich narrative story for this set (500+ words):
      
      ## The World
      Describe the setting, its history, and what makes it unique.
      
      ## The Conflict
      What is the central conflict driving the story?
      
      ## Key Characters
      Introduce 5-8 named characters:
      - At least 2 legendary heroes
      - At least 2 legendary villains
      - Supporting characters
      For each: name, color identity, role, brief description
      
      ## Important Locations
      Name 3-5 significant places
      
      ## Timeline of Events
      What happens during this set's story?
      
      Write immersively - this story will inspire card flavor text and art.
    writes_to: set_story
    cache: true

  - id: generate_card_names
    type: generate_text
    requires: [design_set_mechanics, write_set_story]
    description: "Generate card names and basic info for the set"
    creates_assets: cards  # This step's output populates the 'cards' collection
    prompt: |
      Generate exactly {context.set_size} Magic card names for this set.
      
      SET INFO:
      Theme: {context.set_theme}
      
      Mechanics: 
      {step_outputs.design_set_mechanics}
      
      Story:
      {step_outputs.set_story}
      
      BALANCE REQUIREMENTS:
      - Colors: Distribute evenly across W, U, B, R, G (plus some colorless)
      - Rarities: ~50% Common, ~30% Uncommon, ~20% Rare
      - Types: Mix of creatures, instants, sorceries, enchantments, artifacts
      
      For each card, output as a JSON array with name, type, rarity, and color:
      ```json
      [
        {
          "name": "Moonlit Hunter",
          "card_type": "Creature - Werewolf",
          "rarity": "Uncommon",
          "color": "Green"
        },
        {
          "name": "Cryptborn Curse",
          "card_type": "Enchantment - Aura Curse",
          "rarity": "Rare",
          "color": "Black"
        }
      ]
      ```
      
      Generate all {context.set_size} cards now as a JSON array:
    writes_to: card_names
    cache: true

  - id: generate_card_concepts
    type: generate_text
    for_each: cards
    requires: [generate_card_names]
    description: "Generate concept for {asset.name}"
    prompt: |
      Write a creative concept for this Magic card.
      
      CARD INFO:
      - Name: {asset.name}
      - Type: {asset.card_type}
      - Color: {asset.color}
      - Rarity: {asset.rarity}
      
      SET CONTEXT:
      Theme: {context.set_theme}
      
      Story:
      {step_outputs.set_story}
      
      Write a 2-3 sentence concept describing:
      - Who/what this card represents
      - Their role in the set's story
      - What makes them mechanically interesting
      
      Output ONLY the concept text, no JSON or formatting.
    writes_to: concept
    cache: true

  # Review checkpoint - pause to review set design before card design
  - id: review_set_design
    type: review
    requires: [design_set_mechanics, write_set_story, generate_card_names, generate_card_concepts]
    description: "Review the set design before proceeding to individual card design"
    config:
      title: "Set Design Review"
      description: |
        Review the completed set design work before proceeding to individual card design.
        
        This includes:
        - Set mechanics and thematic framework
        - World narrative and story
        - Card names and concepts for the entire set
        
        Approve to continue with individual card design, or reject to restart the set design phase.
      review_steps:
        - design_set_mechanics
        - write_set_story
        - generate_card_names
        - generate_card_concepts
    cache: true

  # ═══════════════════════════════════════════════════════════════════════════
  # PHASE 2: CARD DESIGN (Per-Asset Steps)
  # ═══════════════════════════════════════════════════════════════════════════

  - id: brainstorm_mechanics
    type: generate_text
    for_each: cards
    requires: [review_set_design]
    description: "Brainstorm mechanics for {asset.name}"
    prompt: |
      Design mechanics for this Magic card:
      
      CARD INFO:
      Name: {asset.name}
      Concept: {asset.concept}
      Type: {asset.card_type}
      Color: {asset.color}
      Rarity: {asset.rarity}
      
      SET MECHANICS AVAILABLE:
      {step_outputs.design_set_mechanics}
      
      TASK: Brainstorm 10 possible mechanics/abilities for this card.
      
      For each mechanic:
      1. Write the oracle text (exactly as it would appear on the card)
      2. Rate complexity (1-5, where 1=vanilla keyword, 5=complex triggered ability)
      3. Rate flavor fit (1-5, how well it matches the concept)
      4. Rate synergy (1-5, how well it supports the set's themes)
      
      Target complexity by rarity:
      - Common: total complexity 2-4
      - Uncommon: total complexity 4-6
      - Rare: total complexity 6-8
      
      Format each as:
      [Number]. [Oracle text]. Complexity [X]. Flavor [X]. Synergy [X].
    writes_to: mechanics_brainstorm
    cache: true

  - id: design_full_card
    type: generate_text
    for_each: cards
    requires: [brainstorm_mechanics]
    description: "Design complete card for {asset.name}"
    prompt: |
      Create the final card design:
      
      CARD INFO:
      Name: {asset.name}
      Concept: {asset.concept}
      Type: {asset.card_type}
      Color: {asset.color}
      Rarity: {asset.rarity}
      
      BRAINSTORMED MECHANICS:
      {asset.mechanics_brainstorm}
      
      DESIGN CONSTRAINTS:
      - Commons: max 2 abilities, total complexity ≤4
      - Uncommons: max 3 abilities, total complexity ≤6
      - Rares: max 4 abilities, total complexity ≤8
      
      MANA COST GUIDELINES:
      - Consider color intensity (more colored mana = stronger color identity)
      - Balance converted mana cost with power level
      - Common creatures: 1-4 CMC typically
      - Rare creatures: can be higher CMC
      
      POWER/TOUGHNESS (if creature):
      - Consider mana cost and abilities
      - Reference similar existing cards
      
      Output the card as JSON:
      ```json
      {
        "name": "{asset.name}",
        "supertype": "Creature/Instant/Sorcery/Enchantment/Artifact/Land",
        "subtype": "If creature: creature types separated by spaces",
        "mana_cost": "{X}{W}{U}{B}{R}{G} format",
        "power": "number or * (creatures only)",
        "toughness": "number or * (creatures only)",
        "rule_text": "Full oracle text with proper MTG formatting",
        "rarity": "{asset.rarity}"
      }
      ```
    writes_to: card_json
    cache: true

  - id: critique_and_refine
    type: generate_text
    for_each: cards
    requires: [design_full_card]
    description: "Review and refine {asset.name}"
    prompt: |
      Review this Magic card design for issues:
      
      {asset.card_json}
      
      CHECK FOR:
      
      1. MISSING DETAILS
         - Does it have mana_cost? (lands exempt)
         - If creature, does it have power/toughness?
         - Is supertype correct?
         
      2. RULES VALIDITY
         - Is the oracle text properly formatted?
         - Are the mechanics mechanically possible?
         - Would a judge understand how to rule on this?
         
      3. POWER LEVEL
         Rate 1-5 (1=unplayable, 3=balanced, 5=overpowered)
         Target: Commons 2-3, Uncommons 2-4, Rares 3-4
         
      4. COMPLEXITY
         Rate 1-5 (1=vanilla, 5=very complex)
         Target: Commons 1-2, Uncommons 2-3, Rares 2-4
         
      5. FLAVOR
         Does the mechanics match the concept?
      
      If any issues found, output the FIXED card JSON.
      If card is good, output "APPROVED" then the original JSON unchanged.
      
      Output only the JSON (with optional APPROVED prefix):
    writes_to: card_refined
    cache: true

  - id: generate_art_direction
    type: generate_text
    for_each: cards
    requires: [critique_and_refine]
    description: "Create art direction for {asset.name}"
    prompt: |
      Create an art prompt for this Magic card:
      
      CARD: {asset.name}
      CONCEPT: {asset.concept}
      CARD DESIGN: {asset.card_refined}
      
      SET STORY:
      {step_outputs.write_set_story}
      
      Think through the art direction:
      
      ## Central Subject
      What is the main focus of the image?
      
      ## Character Details (if applicable)
      - Appearance, clothing, expression
      - Action/pose
      - Cultural influences
      
      ## Scene & Setting  
      - Location/background
      - Time of day, lighting
      - Weather/atmosphere
      
      ## Mood & Tone
      - Emotional feeling
      - Color palette
      - Level of drama/action
      
      ## Style References
      - Art movement or style
      - Reference artists (fantasy artists work well)
      
      Now write the final prompt:
      
      Final Prompt: "[A detailed prompt for image generation, 1-3 sentences]"
      
      Artist Credit: [Artist name to credit on the card, e.g. "inspired by Frank Frazetta"]
    writes_to: art_direction
    cache: true

  - id: write_flavor_text
    type: generate_text
    for_each: cards
    requires: [critique_and_refine]
    description: "Write flavor text for {asset.name}"
    prompt: |
      Write flavor text for this Magic card:
      
      CARD: {asset.name}
      CONCEPT: {asset.concept}
      DESIGN: {asset.card_refined}
      
      SET STORY:
      {step_outputs.write_set_story}
      
      SPACE CONSTRAINTS:
      Look at the rule_text length:
      - Short rules (1-2 lines): Write 2-3 lines of flavor
      - Medium rules (3-4 lines): Write 1-2 lines
      - Long rules (5+ lines): Write 1 short line or skip
      
      FLAVOR OPTIONS:
      1. Quote from a character: "Memorable quote." —Character Name
      2. Brief narrative: Describe a moment or scene
      3. World-building: A fact about the setting
      4. Poetry/verse: Short rhyme or verse
      5. Ominous/atmospheric: Set a mood
      
      Choose the best option and write the flavor text.
      Match the tone of the card (dark for black cards, hopeful for white, etc.)
      
      Output ONLY the flavor text, nothing else:
    writes_to: flavor_text
    cache: true

  # ═══════════════════════════════════════════════════════════════════════════
  # PHASE 3: ART GENERATION (Per-Asset)
  # ═══════════════════════════════════════════════════════════════════════════

  - id: generate_art
    type: generate_image
    for_each: cards
    requires: [generate_art_direction]
    is_output: true
    description: "Generate card art for {asset.name}"
    prompt: |
      Magic: The Gathering card art.
      
      {asset.art_direction}
      
      Style: Fantasy illustration, detailed, painterly, dramatic lighting.
      Do NOT include any text, card frames, or UI elements.
      Focus on the subject matter only.
    # provider: dalle  # Uncomment to use DALL-E instead of default
    writes_to: card_art
    cache: true

  # ═══════════════════════════════════════════════════════════════════════════
  # OPTIONAL: Art Review (uncomment for human-in-the-loop)
  # ═══════════════════════════════════════════════════════════════════════════

  # - id: review_art
  #   type: approve
  #   for_each: cards
  #   requires: [generate_art]
  #   until: approved
  #   max_attempts: 3
  #   message: |
  #     Review art for: {asset.name}
  #     Concept: {asset.concept}
  #     
  #     Does this art match the card's theme and feel?
